Update Bu.yml

diff --git a/.github/workflows/Bu.yml b/.github/workflows/Bu.yml
--- a/.github/workflows/Bu.yml
+++ b/.github/workflows/Bu.yml
@@ -79,27 +79,27 @@ jobs:
             aria2c -q -x 16 -s 16 -k 1M -o kernel-archive "$url"
           fi
 
-      - name: Extract version from downloaded file
+      
       - name: Extract filename from downloaded file
-  id: version_extract
-  run: |
-    if [ -f kernel-archive ]; then
-      filename=$(basename kernel-archive)
-    else
-      files=(kernel-archive-download/*)
-      if [ ${#files[@]} -gt 0 ]; then
-        filename=$(basename "${files[0]}")
-        # move file dari folder download ke kernel-archive supaya proses ekstrak sama
-        mv "${files[0]}" kernel-archive
-        rm -rf kernel-archive-download
-      else
-        echo "ERROR: No downloaded files found"
-        exit 1
-      fi
-    fi
+        id: version_extract
+        run: |
+          if [ -f kernel-archive ]; then
+          filename=$(basename kernel-archive)
+          else
+          files=(kernel-archive-download/*)
+          if [ ${#files[@]} -gt 0 ]; then
+          filename=$(basename "${files[0]}")
+          # move file dari folder download ke kernel-archive supaya proses ekstrak sama
+          mv "${files[0]}" kernel-archive
+          rm -rf kernel-archive-download
+          else
+          echo "ERROR: No downloaded files found"
+          exit 1
+          fi
+          fi
 
-    echo "Filename: $filename"
-    echo "filename=$filename" >> $GITHUB_OUTPUT
+          echo "Filename: $filename"
+          echo "filename=$filename" >> $GITHUB_OUTPUT
 
       - name: Determine archive type and extract accordingly
         run: |
